---
- name: "Install wireguard system-wide"
  ansible.builtin.apt:
    name: wireguard
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: "Ensure no dashes in the interface name"
  when: "'-' in iface_name"
  ansible.builtin.fail:
    msg: "The interface name must not contain dashes, got: '{{ iface_name }}'"

- name: "Create the Hub configuration file"
  no_log: "{{ hide_secrets }}"
  notify: "Run the Wireguard service"
  ansible.builtin.blockinfile:
    path: "/etc/wireguard/{{ iface_name }}.conf"  # Wg does not permit dashes
    create: true
    owner: root
    group: root
    mode: "0600"
    state: present
    block: |
      [Interface]
      Address = {{ ipv4_vpn_addr }}/{{ ipv4_vpn_cidr }}
      ListenPort = {{ wg_port }}
      PrivateKey = {{ wg_pkey }}

      PreUp = sysctl -w net.ipv4.ip_forward=1
      PostDown = sysctl -w net.ipv4.ip_forward=0

- name: "Add [Peer] sections to the Hub configuration file"
  no_log: "{{ hide_secrets }}"
  notify: "Run the Wireguard service"
  loop: "{{ peers }}"
  ansible.builtin.blockinfile:
    path: "/etc/wireguard/{{ iface_name }}.conf"  # Wg does not permit dashes
    owner: root
    group: root
    mode: "0600"
    marker: "# {mark} ANSIBLE MANAGED SPOKE BLOCK: {{ item.host_id }}.{{ iface_name }}.vpn"
    block: |
      #
      [Peer]  # {{ item.host_id }}
      PublicKey = {{ item.wg_pubkey }}
      AllowedIPs = {{ item.ipv4_vpn_addr }}/32
      #
