---
name: molecule
  
on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:

  molecule:
    name: molecule
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        distro:
          - ubuntu2204
          - ubuntu2004

    steps:
      - uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@ab6bf8bf7403e8023a094abeec19d6753bdc143e
        with:
          micromamba-version: '1.5.8-0'
          environment-file: conda.dev.yml
          init-shell: bash
          post-cleanup: 'all'

      - name: "Install role dependencies"
        run: ansible-galaxy install -r requirements.yml
        shell: micromamba-shell {0}

      - name: "Run Molecule tests"
        run: molecule test
        shell: micromamba-shell {0}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
